theme: jekyll-theme-architect

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  email:
  github: paruff/microservices
  linkedin:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-508750-23

# Set the Sass partials directory, as we're using @imports
#sass:
#  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
 gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
#  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
#exclude:
#  - Gemfile
#  - Gemfile.lock
#  - LICENSE
#  - README.md
#  - CNAME
